config/routes.rb
ProfcynGallery::Application.routes.draw do

  root :to => 'galleries#index'

  resources :galleries, :only => [:index, :show]

end

app/models/gallery.rb
# encoding: UTF-8

class Gallery < ActiveRecord::Base

  has_many :images

  before_validation :create_slug

  validates :name, :presence => true
  validates :slug, :presence => true

  private
 
    def create_slug
      self.slug = self.name.underscore.parameterize(sep = '-')
    end

end

app/models/image.rb
class Image < ActiveRecord::Base
  attr_accessible :description, :height, :url, :taken_at, :title, :width, :location, :gallery, :local_path

  belongs_to :location
  belongs_to :gallery
end

app/models/location.rb
class Location < ActiveRecord::Base
  attr_accessible :city, :country, :kind, :region
  has_many :images
end

app/models/settings.rb
class Settings < Settingslogic
  source "#{Rails.root}/config/settings.yml"
  namespace Rails.env
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery
  http_basic_authenticate_with :name => Settings.htaccess.user, :password => Settings.htaccess.password unless Rails.env.development? || Rails.env.test?

  private
    def init_dropbox_client
      @client = Dropbox::API::Client.new(:token => Settings.dropbox.token, :secret => Settings.dropbox.secret)
    end

end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController

  def index
    @galleries = Gallery.all
  end

  def show
    @galleries = Gallery.all
    @gallery = @galleries.find{|e| e.slug == params[:id]}
    gon.gallery = @gallery
    gon.images = @gallery.images
  end

end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

  def index
    @location = Location.find_by_country(params[:location_id] || 'taiwan')
    @images = @location.images.limit(10)
    gon.images = @images
    gon.rabl :template => 'app/views/images/index.rabl'
  end

  def show
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/galleries/index.html.haml
%h1 Galleries
%ul.m-galleries-list
  - @galleries.each do |gallery|
    %li
      = link_to gallery.title, gallery_path(gallery.slug), :class => 'm-gallery-list-item'

app/views/galleries/show.html.haml
.m-gallery-switcher
  - @galleries.each_with_index do |gallery, index|
    :erb
      <%= link_to gallery.title, gallery_path(gallery.slug), :class => 'm-gallery-switcher-item' %><%= index == @galleries.size-1 ? nil : ' | ' %>

.m-gallery

app/views/images/create.html.haml
%h1 Images#create
%p Find me in app/views/images/create.html.haml

app/views/images/destroy.html.haml
%h1 Images#destroy
%p Find me in app/views/images/destroy.html.haml

app/views/images/edit.html.haml
%h1 Images#edit
%p Find me in app/views/images/edit.html.haml

app/views/images/new.html.haml
%h1 Images#new
%p Find me in app/views/images/new.html.haml

app/views/images/show.html.haml
%h1 Images#show
%p Find me in app/views/images/show.html.haml

app/views/images/update.html.haml
%h1 Images#update
%p Find me in app/views/images/update.html.haml

app/views/layouts/application.html.haml
!!! 5
%html{lang: 'en'}
  %head
    %title ProfCyn Gallery
    %meta{charset: 'utf-8'}/
    %link{rel: 'shortcut icon', href: '/favicon.ico'}

    = stylesheet_link_tag 'application'
    - if Rails.env.development?
      = stylesheet_link_tag 'development'
    /[if lt IE 9]
      = stylesheet_link_tag 'ie'
    = include_gon(:camel_case => true)
    = javascript_include_tag 'application'
    = csrf_meta_tags

  %body{:class => "#{controller_name} #{action_name}"}
    .main-content-wrapper
      = yield

app/views/pages/index.html.haml
.gallery
  %h1 Photos from Taiwan &amp; Thailand

  - @images.each do |image|
    = image_tag image.url